name: spacex_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: ^2.0.1
  # Bloc for state management
  flutter_bloc: ^0.21.0
  # Value equality
  equatable: ^0.4.0
  # Functional programming thingies
  dartz: ^0.8.6
  # Remote API
  data_connection_checker: ^0.3.4

  # Local cache
  hive: ^1.0.0
  hive_flutter: ^0.2.1

  # Graph Client
  graphql_flutter: ^2.1.0

  cupertino_icons: ^0.1.2
  path_provider: ^1.3.0
  json_serializable: ^3.2.3

  logger: ^0.7.0+2

dev_dependencies:
  build_runner: ^1.7.1
  hive_generator: ^0.5.1
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0

flutter:

  uses-material-design: true